version: '3'
services: 
  visualizer:
    image: dockersamples/visualizer
    ports:
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.rolue==manager

  agent:
    image: portainer/agent
    environment: 
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    ports: 
      - 9001
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os==linux

  portainer:
    image: portainer/portainer
    depends_on:
      - agent
    ports: 
      - 9000:9000
      - 8000:8000
    volumes: 
      - portainer_data:/data
    command:
      -H tcp://tasks.agent:9001 --tlsskipverify
      # -H tcp://agent:9001 --tlsskipverify
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.rolue==manager

volumes: 
  portainer_data:
